-- Relic — 10 SEED ACCOUNTS (realistic names, e.g. "Ingrid Solberg") with public activities,
-- so a small beta has people to follow. Kept until there are enough real users.
-- Generated by a script; run in the Supabase SQL Editor. Safe to re-run.
-- Sign in as any of them: user1@example.com … user10@example.com
--                         password: relic-test-1234
-- Remove them all again: docs/dev/seed-test-users-cleanup.sql
-- Run AFTER supabase-social-v2.sql if you want the kudos/comments part.

-- User 1
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000001', 'authenticated', 'authenticated', 'user1@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', '{"sub":"a0000000-0000-4000-8000-000000000001","email":"user1@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000001', 'Ingrid Solberg', 'Morning runner · Oslo')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_1_0', 'a0000000-0000-4000-8000-000000000001', 'Afternoon ride in Oslo', 'Ride', now() - interval '1 days 6 hours', 'manual', 24470, 3263, 68, 'ep|lJavl`Awc@fLqc@|Mkd@zD}b@fRa`@|^k_@|`@i\di@qYrn@aRby@iXxp@}Z~k@mVvs@oQty@w[jj@{Wnq@sXhp@aNx|@gEpaA_Pd{@qOn{@qC~aAd@nbAlDvaAtF`aAdR~x@n[zj@zXzo@`Upu@j\~h@~Xto@nPrz@~J|~@|Hb`AzBbbAlOt{@~Pdz@tVjs@f^hd@bUlu@', 59.95283, 10.71985, true, 'Legs felt great today.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000001' and id = 'seed_1_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_1_1', 'a0000000-0000-4000-8000-000000000001', 'Hike in Oslo', 'Hike', now() - interval '5 days 2 hours', 'manual', 10631, 8178, 897, 'o}wlJuvr`AmMsIwLkLuKkOyLeLmNeCoN{BkMaJyL_LmKcPiJkRsIsS_H_ViHqUmI_TuFmWuJuQiJmR{LyKsM_IcNcFeNwEcNuEsNmAaNhFkN`DuMpHmNdCgN`EqNvAsN_@oNoBoNbBiMhJqNzAsMzHsNPsNo@wMeHgKmP', 59.92936, 10.75067, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000001' and id = 'seed_1_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_1_2', 'a0000000-0000-4000-8000-000000000001', 'Evening walk in Oslo', 'Walk', now() - interval '9 days 7 hours', 'manual', 9948, 7106, 192, 'skulJqhs`AiFzWiAxZnAvZ`F`X~I~R|LrKbNbFdMzJpIvS`G`WbBpZ_BpZs@~Z{CvY}@zZaAzZFb[_BrZv@|Zo@~ZcBpZx@|Z}ArZaBpZyGfVaCdZmAvZxAtZcBpZz@zZaA|ZxBfZpC|YrElX|BdZNb[cBpZkAxZsFpW', 59.91626, 10.75353, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000001' and id = 'seed_1_2'
on conflict (user_id, activity_id) do nothing;

-- User 2
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000002', 'authenticated', 'authenticated', 'user2@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000002', '{"sub":"a0000000-0000-4000-8000-000000000002","email":"user2@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000002', 'Erik Haugland', 'Weekend bikepacker · Bergen')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_2_0', 'a0000000-0000-4000-8000-000000000002', 'Hike in Bergen', 'Hike', now() - interval '2 days 2 hours', 'manual', 10325, 7942, 434, 'kzqoJwks_@qBkZ`@a[i@a[aE{XMc[cDqYcH{UiLwMkNiDsNRqNe@eNwEsNw@cNxEmNpCqNk@qNoBiNdDgNlEoNbBiNzDkMzIaNlFcMbKoMnImN~BsNEoMlIeJtR{HvT_E~X[`[qCzYyAtZcF`XcF~WoErXgBnZfAxZ', 60.38966, 5.34732, true, 'Perfect weather for it.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000002' and id = 'seed_2_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_2_1', 'a0000000-0000-4000-8000-000000000002', 'Evening walk in Bergen', 'Walk', now() - interval '6 days 10 hours', 'manual', 10309, 7364, 114, 'q{noJe}n_@xLbLzL|K`NrFlMnIjNbDfL~MtJpQ`K|PjHnUlJbRnHhUvElXlGrVtFnWtAtZ~D~XlHjU~KpNbNfFnNfBbNaFnNpBpNgAlNqCvMmHhKiP|M_GrN?vMhHlK~OtGjV`BrZhC~YhHrU|D~Xn@~ZeAzZ?b[eBnZ', 60.37449, 5.32451, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000002' and id = 'seed_2_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_2_2', 'a0000000-0000-4000-8000-000000000002', 'Morning run in Bergen', 'Run', now() - interval '10 days 7 hours', 'manual', 10244, 3532, 142, 'kxroJkdo_@rNAtMtHdL`NzMxGpNu@fNbEnNmBnNsBlNxChMbJxM|G`LpNjHlU~EbXrGnVdHvU|G`VdL~MtHbUxGfVvEhXXb[gDnYgEvXoIxSwKhO}G~U}D~XyAtZqBjZZb[lErXrHbUbJtRxJnQjI|SpHhUnHhUlHjU', 60.39446, 5.32566, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000002' and id = 'seed_2_2'
on conflict (user_id, activity_id) do nothing;

-- User 3
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000003', 'authenticated', 'authenticated', 'user3@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000003', '{"sub":"a0000000-0000-4000-8000-000000000003","email":"user3@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000003', 'Sofie Lund', 'Chasing summits · Trondheim')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_3_0', 'a0000000-0000-4000-8000-000000000003', 'Evening walk in Trondheim', 'Walk', now() - interval '3 days 3 hours', 'manual', 9905, 7075, 29, 'ifdbKwip~@`MgKlI}S~I_SbJwRlEsXTc[nAwZjFwWbH{UxCwYhAyZSa[eE{XiHsUaE{X_BsZoEoXy@_[wEiX{HwTeJwRyK_OcLkNuKmOwM_HaNsFsNTmNoCsNIqNw@oNcCkM{IyM_HkLoMgNeEsN^qNsAsNn@sMvH', 63.43285, 10.41068, true, 'Found a new favourite loop.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000003' and id = 'seed_3_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_3_1', 'a0000000-0000-4000-8000-000000000003', 'Morning run in Trondheim', 'Run', now() - interval '7 days 7 hours', 'manual', 9454, 3260, 198, 'mb`bKoys~@qDiYuFmWsJ{QmGsViDoYaImTyJkQ{GeVqC{Y_E}XCc[_CeZaDsY}FgWuBiZq@_[eCaZgHsUwH_UsIuSyK_OcM_KcNcFkN}CwLmLeIiTgJqRqGoVkHoUwEkXoBkZ}CuYkEsXyH_U_FcXcJwRqEqXsGmVsFqW', 63.41175, 10.42856, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000003' and id = 'seed_3_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_3_2', 'a0000000-0000-4000-8000-000000000003', 'Afternoon ride in Trondheim', 'Ride', now() - interval '11 days 8 hours', 'manual', 22936, 3058, 241, 'm_`bKgts~@hHk`AlJi_ARmbA_G}`AqMg}@yWsq@w^{b@{Xyo@g]}f@aVgt@gLc~@wWuq@e`@q^_Xiq@iMk}@oFcaAuRmx@e[qk@cb@qVg_@ka@wYgn@gNu|@mMi}@aO_|@yDuaAOobA@obAdG{`AlSsw@f]wf@xb@iSja@yYxa@eXh]wf@xX_p@pXkp@zSaw@pVqs@xScw@', 63.41127, 10.42772, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000003' and id = 'seed_3_2'
on conflict (user_id, activity_id) do nothing;

-- User 4
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000004', 'authenticated', 'authenticated', 'user4@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000004', '{"sub":"a0000000-0000-4000-8000-000000000004","email":"user4@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000004', 'Jonas Berg', 'Coffee, then trails · Stavanger')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_4_0', 'a0000000-0000-4000-8000-000000000004', 'Morning run in Stavanger', 'Run', now() - interval '4 days 3 hours', 'manual', 10604, 3657, 115, 'gz}fJa_cb@dHxUhC~Y|EdXnGpVxFjWfGzV`FbX~EbXnAvZ{AtZyFjWiHpUyIhSeLbNcKrPoMlIsNRqMkIoNaBkNfDkN}CsN^oNaBkNeDoN|BoMjIsNKoMlImN`CcNfFiNtDkNyCeMyJgNkEqNWgNiEsNt@{MpGkNrC', 58.97652, 5.75489, true, 'Worth the early start.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000004' and id = 'seed_4_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_4_1', 'a0000000-0000-4000-8000-000000000004', 'Afternoon ride in Stavanger', 'Ride', now() - interval '8 days 3 hours', 'manual', 25498, 3400, 193, 'ky~fJs{|a@nVqs@`Mq}@xC}aAqC_bAcK{~@kWir@k[ak@yVcs@k[ek@sW{q@w^_c@gX}p@y^sb@ca@a[{c@{Jwc@qLod@fA{b@vRkd@sC_c@}Qm_@}`@aVgt@yWqq@_^}d@_`@a_@uc@gMkd@jDmb@|Tkd@nEad@zHgd@tFod@p@md@rBic@~Occ@|P}c@vJ}c@xJod@}@cd@~G', 58.9815, 5.72362, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000004' and id = 'seed_4_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_4_2', 'a0000000-0000-4000-8000-000000000004', 'Hike in Stavanger', 'Hike', now() - interval '12 days 1 hours', 'manual', 10468, 8052, 616, 'gd}fJoqza@jI~SrGnVpHdUhIdTnJ~QbKvP~G~UxDbYd@~Z[`[Xb[jDlY~EbXvDbY|BfZtAtZ}@zZcEzXwIlS_J~R_K|PsM`I{LxKmMzIsM|HsNd@{MrGmNvBsNUyM_HeLaNwKgOgIeTgJqR{JgQuLqLaNuF_NyFsNJ', 58.973, 5.71176, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000004' and id = 'seed_4_2'
on conflict (user_id, activity_id) do nothing;

-- User 5
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000005', 'authenticated', 'authenticated', 'user5@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000005', '{"sub":"a0000000-0000-4000-8000-000000000005","email":"user5@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000005', 'Maja Nilsen', 'Northern lights hunter · Tromsø')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_5_0', 'a0000000-0000-4000-8000-000000000005', 'Afternoon ride in Tromsø', 'Ride', now() - interval '5 days 7 hours', 'manual', 19791, 2639, 77, 'utchLghyrBfHm`AfNu|@XobAfMk}@lWgr@n[{j@nSqw@pHg`A~AibAr@mbAhHk`AjGy`A@obAlHi`ADobAiDyaAuFaaAeS}w@aNy|@i@mbAiGy`AwGs`AaK}~@iP{z@_Uuu@uHe`AqNm|@eZmm@g`@i^kb@mU_c@}Qu_@_`@ma@uYeb@gVqa@iYqYsn@a`@{^_b@mWod@V', 69.65595, 18.9762, true, 'Views all the way.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000005' and id = 'seed_5_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_5_1', 'a0000000-0000-4000-8000-000000000005', 'Hike in Tromsø', 'Hike', now() - interval '9 days 3 hours', 'manual', 7726, 5943, 684, 'mybhL_ozrB|CtYfC`ZlBlZeAzZk@~ZdAzZfEvXd@`[e@`[F`[Wb[_BrZoDhYaIlTiJlR{JjQsInSuIpSgIfT{IdSuH`UkDjY?b[Kb[tBhZbHxUpIvStH`UzIfSfEvXtBhZcAzZbAzZuAtZ{D`Y{BfZcF`XoHhUsKnO', 69.65159, 18.9824, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000005' and id = 'seed_5_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_5_2', 'a0000000-0000-4000-8000-000000000005', 'Evening walk in Tromsø', 'Walk', now() - interval '13 days 2 hours', 'manual', 9173, 6552, 26, 'ytdhLclxrByH{TcKsP{MuGkKePsHeUmC}YyH}TqHgUeF}WoFuWyIgSqKwOkMaJ}IcS_FeXgGyVwImSoEqX_CeZyAuZaE}XaGcWkHmUsDgYgIgT_MmKsM_IkNeD_MmKmNcCiMmJiLqMoMqIaMgK{L}KqNoAoNuBqNqAsN`@', 69.66109, 18.9717, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000005' and id = 'seed_5_2'
on conflict (user_id, activity_id) do nothing;

-- User 6
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000006', 'authenticated', 'authenticated', 'user6@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000006', 'a0000000-0000-4000-8000-000000000006', 'a0000000-0000-4000-8000-000000000006', '{"sub":"a0000000-0000-4000-8000-000000000006","email":"user6@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000006', 'Henrik Dahl', 'Ski season is the best season · Lillehammer')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_6_0', 'a0000000-0000-4000-8000-000000000006', 'Hike in Lillehammer', 'Hike', now() - interval '6 days 3 hours', 'manual', 10344, 7957, 162, 'ulctJmow~@yGdVgKpPiKdPiKhPaNrF{MpGgL~MsLtL_NvFsN{@qNd@sNI}MmGsNc@gMqJoNsAsNhAkMxIoLdMeKrPcHxUgJpRqHdU}HvTyL`LkN~CoNcCuLoLyLeL}IaSgG{VuEkXmGwVqDgYoAyZaDqY}FgWyH{T{K_O', 61.13499, 10.44743, true, 'Slow and steady.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000006' and id = 'seed_6_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_6_1', 'a0000000-0000-4000-8000-000000000006', 'Evening walk in Lillehammer', 'Walk', now() - interval '10 days 1 hours', 'manual', 9917, 7084, 175, 'qo_tJku{~@`G`WvJtQ`M`KrLzLrKpObN~ErNt@|MaGpNgAbMgK~I}R~G_VfG{VrEmX|@{ZxDeY|D}XtEmXlBmZJc[_A{ZkBoZvAuZfDoY`A{Zh@_[zEgXhEwXb@a[~EcXp@_[Mc[c@a[mDiY_IuTiLsMuHaU}JcQyIiS', 61.11497, 10.46886, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000006' and id = 'seed_6_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_6_2', 'a0000000-0000-4000-8000-000000000006', 'Morning run in Lillehammer', 'Run', now() - interval '14 days 6 hours', 'manual', 10106, 3485, 170, 'au}sJcuz~@qNhAsNEmM{I{L}KkLqM{MmGsNk@kMaJ_MiKmMwI_N_GaLkN}HwT}GaVyBgZ_@a[aBsZXa[}CuYeHuUyH}TcE{XgDoYoFsWaDsYiCaZ}@{ZQc[dBqZzGeVlJaRjI_TzGeV|KwNdHyUvKeO|MkGxL_LtKoO', 61.10561, 10.4637, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000006' and id = 'seed_6_2'
on conflict (user_id, activity_id) do nothing;

-- User 7
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000007', 'authenticated', 'authenticated', 'user7@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000007', 'a0000000-0000-4000-8000-000000000007', 'a0000000-0000-4000-8000-000000000007', '{"sub":"a0000000-0000-4000-8000-000000000007","email":"user7@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000007', 'Freja Madsen', 'City cyclist · Copenhagen')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_7_0', 'a0000000-0000-4000-8000-000000000007', 'Evening walk in Copenhagen', 'Walk', now() - interval '7 days 0 hours', 'manual', 10918, 7799, 140, 'u_wrIao{kAiMiJiLuM_J_ScEyXaA{ZcA{ZwFoWsBiZ{BgZmDkY[a[}DaY{FgWcIkTsLyLsM{HoK{OsJyQeJuR_H_VcDqY_CeZkFwW{GcVsIsSeLgN}M_GcNgFkKePaJ{RiMiJ_NyFqNqAkNxCqNrA{MnGiNpDgNhEmNqC', 55.66475, 12.59777, true, 'Short but sweet.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000007' and id = 'seed_7_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_7_1', 'a0000000-0000-4000-8000-000000000007', 'Morning run in Copenhagen', 'Run', now() - interval '11 days 5 hours', 'manual', 10881, 3752, 160, 'sizrImwukAaLlNwMbHuMxHsN^uMqHoNsBqNgAmNrC_MfKaLpNaJxRyFjW_H~UmC|Y}D~XkFxW{JfQsMdIqNj@yM_HaNkFoNmBsM_IkJiRwEkXyGgV}KyN}M}FsN]yM|GsLxLgLxMmK`P}MnGiNhDkNxCkNhDiNtD_NtF', 55.6817, 12.56839, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000007' and id = 'seed_7_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_7_2', 'a0000000-0000-4000-8000-000000000007', 'Afternoon ride in Copenhagen', 'Ride', now() - interval '15 days 9 hours', 'manual', 26249, 3500, 239, '{rwrIkhykAhd@rEnd@mAda@qZzc@iKtc@`M~`@r[|Xto@vWtq@l[~j@p]bf@|[zi@la@|YrYln@t_@``@rc@lMfc@lPta@pXn]lf@r_@b`@~Wfq@`Sbx@|V|r@bLf~@zM||@pXjp@lL`~@|Vzr@rPrz@fSxw@hFdaAlQxy@nTfv@dNv|@dQ`z@bMn}@rMb}@hKx~@fWlr@v]re@', 55.66782, 12.58646, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000007' and id = 'seed_7_2'
on conflict (user_id, activity_id) do nothing;

-- User 8
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000008', 'authenticated', 'authenticated', 'user8@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000008', 'a0000000-0000-4000-8000-000000000008', 'a0000000-0000-4000-8000-000000000008', '{"sub":"a0000000-0000-4000-8000-000000000008","email":"user8@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000008', 'Linnea Ek', 'Island hopper · Stockholm')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_8_0', 'a0000000-0000-4000-8000-000000000008', 'Morning run in Stockholm', 'Run', now() - interval '8 days 8 hours', 'manual', 10249, 3534, 166, '{`aiJcdbmB{BdZ}AtZ_E|XcF~W}D~Xy@|ZsBjZaGbWgJnRgLxMkNnDmLdMyJlQmI|S_FdXgJlRiIbTkEtXgIfTuInS{JfQmHnUuFlWkAxZyFjWkJfR}FfW}BfZmAvZaF`XaFbXsFpW{CtYaBrZ{D`YgIdToLdM{LxKuIpS', 59.32062, 18.03858, true, 'Golden hour.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000008' and id = 'seed_8_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_8_1', 'a0000000-0000-4000-8000-000000000008', 'Afternoon ride in Stockholm', 'Ride', now() - interval '12 days 9 hours', 'manual', 25601, 3413, 70, 'oodiJstlmBjd@rCdd@_Htb@{Spb@iT~`@k[`^}d@l\yh@ja@{Yh[gk@hV{s@p\qh@t^ac@bc@iQx^ub@nb@}Tpc@wMp_@k`@f\ki@bWsr@|^ib@~[yi@fUiu@h_@ma@b[qk@`]mg@ta@oXnd@Grc@jMjc@pObd@oHrc@qMpb@iTld@jBfd@vFhb@zUnd@i@xb@`Sr_@d`@pa@fY', 59.33832, 18.09242, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000008' and id = 'seed_8_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_8_2', 'a0000000-0000-4000-8000-000000000008', 'Hike in Stockholm', 'Hike', now() - interval '16 days 9 hours', 'manual', 10362, 7971, 368, 'ij`iJkudmBdIiTfKoPzMoGfL_NtLoLjM}IvJsQpIwSnGqVpEoXjGwV|BgZ`@_[bFcXxEgXjJkRnJ}QtKkO|IcS~I_SjM_JfJoRdF_X`CcZzBgZvAuZjAyZ?c[_CeZ{@}ZaCcZaH}UaJ{R}KwNwMkHkN_DoNbBgN{DkN_D', 59.31701, 18.05158, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000008' and id = 'seed_8_2'
on conflict (user_id, activity_id) do nothing;

-- User 9
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000009', 'authenticated', 'authenticated', 'user9@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000009', 'a0000000-0000-4000-8000-000000000009', 'a0000000-0000-4000-8000-000000000009', '{"sub":"a0000000-0000-4000-8000-000000000009","email":"user9@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000009', 'Callum Reid', 'Hill walker · Edinburgh')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_9_0', 'a0000000-0000-4000-8000-000000000009', 'Afternoon ride in Edinburgh', 'Ride', now() - interval '9 days 10 hours', 'manual', 26066, 3475, 124, 'gtqtId}rRqa@hYmd@z@ad@tIyc@qKsc@wMc_@wa@eVat@aNy|@yOi{@}Twu@e\ki@}Umt@aJo_AaG}`AbD{aAwEkaAmOu{@sPqz@_[{k@ib@}Ukd@kCub@ySgd@kGgd@yFac@nQkd@hDab@~Vkd@tDo`@h]sa@~Xsa@vXod@l@yc@_Lyc@uKod@H{b@tRyc@`Lmc@vNi`@|]', 55.965, -3.21507, true, 'Windy, but worth it.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000009' and id = 'seed_9_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_9_1', 'a0000000-0000-4000-8000-000000000009', 'Hike in Edinburgh', 'Hike', now() - interval '13 days 4 hours', 'manual', 10875, 8365, 874, 'umntIv~lReCbZkHlUoHhU{IfSyJjQcHzUuGjViC~YqGpVaJxRcG~VoIxSwH`UmIzSwGjVsGjVmI|SmLjM_MlKaMlKiKfPuMpH{K~NyMzGoK|OcLdNoKzOeKpPoKzO_K`Q}MhGcNzEcLfNmLjMyJlQyJjQuMtHyM~G_NvF', 55.94859, -3.1846, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000009' and id = 'seed_9_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_9_2', 'a0000000-0000-4000-8000-000000000009', 'Evening walk in Edinburgh', 'Walk', now() - interval '17 days 1 hours', 'manual', 10877, 7769, 205, 'gwltI`unRgJqRgHuUiLwM}I_SuGmVcKuP_LqNeNsEsNTyMdHaNlFqN~@qN|@mNoCsNZmNbCsNn@_NxFwMhHwJrQoMhImK~OcJxRaIlTwJrQiKfPuHbUeC`Z}AtZw@|Z|@zZ}@|ZY`[kAxZtAtZ|CvYhHpUfEvXbHzU', 55.93988, -3.19329, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000009' and id = 'seed_9_2'
on conflict (user_id, activity_id) do nothing;

-- User 10
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000010', 'authenticated', 'authenticated', 'user10@example.com',
  extensions.crypt('relic-test-1234', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}',
  now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000010', 'a0000000-0000-4000-8000-000000000010', 'a0000000-0000-4000-8000-000000000010', '{"sub":"a0000000-0000-4000-8000-000000000010","email":"user10@example.com","email_verified":true}', 'email', now(), now(), now())
on conflict do nothing;
insert into public.profiles (id, name, bio) values ('a0000000-0000-4000-8000-000000000010', 'Chloé Bernard', 'Alpine everything · Chamonix')
on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_10_0', 'a0000000-0000-4000-8000-000000000010', 'Hike in Chamonix', 'Hike', now() - interval '10 days 6 hours', 'manual', 13264, 10203, 624, 'objwGml~h@rDfYfEvXjFxWn@~Z_BpZp@~Z~@zZiAxZe@`[Pb[kDjYuCzYmFvWgHrUoIxSyHzTwH`UiEtXwH|TiDnYyD`Y{D`YWb[^`[dDnYXb[lErXt@|ZfDnY|BdZFb[b@`[t@~ZbC`Z[b[~BdZtAtZdExXhHpU', 45.93208, 6.87831, true, 'Best one this month.')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000010' and id = 'seed_10_0'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_10_1', 'a0000000-0000-4000-8000-000000000010', 'Evening walk in Chamonix', 'Walk', now() - interval '14 days 9 hours', 'manual', 12614, 9010, 177, 'kydwGgk`i@jEvXtBhZ~@zZtDdYzD`YbBpZ|CtYjErXlFvW`DrYnHhUhLvM`JzRnLbMlNnCnNsBnNpBtMtHlK~OdJrRvKfO~MvFjKdPpMdIpMfIrJvQbF~WjEvXjFxWl@~Z@b[Y`[gBnZ}BfZk@~ZuCxYaIpT_DrYm@~Z', 45.90502, 6.88836, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000010' and id = 'seed_10_1'
on conflict (user_id, activity_id) do nothing;
insert into public.activities (id, user_id, name, type, date, source, distance, duration, elevation, polyline, start_lat, start_lng, is_public, note)
values ('seed_10_2', 'a0000000-0000-4000-8000-000000000010', 'Morning run in Chamonix', 'Run', now() - interval '18 days 3 hours', 'manual', 12288, 4237, 199, 'kzewGog{h@uLrLsHdUcC`ZuFnWiGzVmFtWqGnVmJfRoGpVsDfYuElXkJfRoIxSwKhOgMpJgJnRmIzSoEpXgJnR}GbVcF~WoC|Y_IrTmJdRaH|UeHtUsCzYwGhVoIzSaMfKgN`EyM|GaLjNcNbFeLbNmLfMqMhIuMvHiNjD', 45.9103, 6.86216, true, '')
on conflict (user_id, id) do nothing;
insert into public.activity_public (user_id, activity_id, name, type, date, distance, duration, elevation, note, polylines)
select user_id, id, name, type, date, distance, duration, elevation, note, array[polyline] from public.activities where user_id = 'a0000000-0000-4000-8000-000000000010' and id = 'seed_10_2'
on conflict (user_id, activity_id) do nothing;

-- Test users follow each other (each follows the next three)
insert into public.follows (follower_id, followee_id)
select a.id, b.id from (values (1,'a0000000-0000-4000-8000-000000000001'::uuid),(2,'a0000000-0000-4000-8000-000000000002'::uuid),(3,'a0000000-0000-4000-8000-000000000003'::uuid),(4,'a0000000-0000-4000-8000-000000000004'::uuid),(5,'a0000000-0000-4000-8000-000000000005'::uuid),(6,'a0000000-0000-4000-8000-000000000006'::uuid),(7,'a0000000-0000-4000-8000-000000000007'::uuid),(8,'a0000000-0000-4000-8000-000000000008'::uuid),(9,'a0000000-0000-4000-8000-000000000009'::uuid),(10,'a0000000-0000-4000-8000-000000000010'::uuid)) a(n, id)
join (values (1,'a0000000-0000-4000-8000-000000000001'::uuid),(2,'a0000000-0000-4000-8000-000000000002'::uuid),(3,'a0000000-0000-4000-8000-000000000003'::uuid),(4,'a0000000-0000-4000-8000-000000000004'::uuid),(5,'a0000000-0000-4000-8000-000000000005'::uuid),(6,'a0000000-0000-4000-8000-000000000006'::uuid),(7,'a0000000-0000-4000-8000-000000000007'::uuid),(8,'a0000000-0000-4000-8000-000000000008'::uuid),(9,'a0000000-0000-4000-8000-000000000009'::uuid),(10,'a0000000-0000-4000-8000-000000000010'::uuid)) b(n, id)
  on b.n in (((a.n) % 10) + 1, ((a.n + 1) % 10) + 1, ((a.n + 2) % 10) + 1)
on conflict do nothing;

-- Your own account: Users 1–5 follow you, you follow Users 1–6.
-- (Uses your sign-in email; change it here if you use a different account.)
insert into public.follows (follower_id, followee_id)
select t.id, me.id from auth.users me, auth.users t
where me.email = 'tysemitchbin@gmail.com' and t.email in ('user1@example.com','user2@example.com','user3@example.com','user4@example.com','user5@example.com')
on conflict do nothing;
insert into public.follows (follower_id, followee_id)
select me.id, t.id from auth.users me, auth.users t
where me.email = 'tysemitchbin@gmail.com' and t.email in ('user1@example.com','user2@example.com','user3@example.com','user4@example.com','user5@example.com','user6@example.com')
on conflict do nothing;

-- Some kudos + comments between test users (only if supabase-social-v2.sql has been run)
do $$ begin
  if to_regclass('public.kudos') is not null then
    insert into public.kudos (activity_user_id, activity_id, user_id)
    select p.user_id, p.activity_id, f.follower_id from public.activity_public p
    join public.follows f on f.followee_id = p.user_id
    where p.activity_id like 'seed_%_0' and f.follower_id::text like 'a0000000-%'
    on conflict do nothing;
  end if;
  if to_regclass('public.comments') is not null then
    insert into public.comments (activity_user_id, activity_id, user_id, body)
    select p.user_id, p.activity_id, f.follower_id, 'Looks great! 🙌' from public.activity_public p
    join public.follows f on f.followee_id = p.user_id
    where p.activity_id like 'seed_%_1' and f.follower_id::text like 'a0000000-%'
      and not exists (select 1 from public.comments c where c.activity_user_id = p.user_id and c.activity_id = p.activity_id and c.user_id = f.follower_id);
  end if;
end $$;
